apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: homework-volume
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'wget -O /init/index.html http://example.com']
      volumeMounts:
        - name: homework-volume
          mountPath: /init
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: homework-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework/index.html"]

